#
# Copyright 2025-2026 Infradise Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Keyscope:
# - A high-performance GUI for Redis, Valkey, and Dragonfly. 
# - Provides support for Cluster, Sentinel, SSH/TLS, and handling millions of keys. 
# - Built on top of keyscope_client, a Dart library for Redis, Valkey, Dragonfly.

name: keyscope
description: Redis, Valkey, and Dragonfly GUI with built-in multilingual support for global users.
version: 0.8.3
homepage: https://github.com/infradise/keyscope
repository: https://github.com/infradise/keyscope
issue_tracker: https://github.com/infradise/keyscope/issues
documentation: https://github.com/infradise/keyscope/blob/main/CLI.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  # sdk: 3.11.0
  # flutter: 3.41.0

# [CLI Configuration]
# Maps the 'keyscope' command to 'bin/keyscope.dart'
executables:
  keyscope: keyscope

dependencies:
  args: ^2.7.0 # Add this for CLI argument parsing
  # envied: ^1.3.2
  flutter:
    sdk: flutter
  # flutter_json_view: ^1.1.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  # flutter_secure_storage: ^10.0.0
  # flutter_svg: ^2.2.3
  # freezed_annotation: ^3.1.0
  # gap: ^3.0.1
  # intl: ^0.20.2
  keyscope_client: ^4.2.0
  # --- for debugging ---
  # keyscope_client:
  #   path: ../keyscope_client
  # keyscope_client:
  #   git:
  #     url: https://github.com/infradise/keyscope_client
  #     ref: main
  # shared_preferences: ^2.5.4
  # system_theme: ^3.2.0
  # toastification: ^3.0.3
  # uuid: ^4.5.2

dev_dependencies:
  # build_runner: ^2.10.5
  dart_flutter_team_lints: ^3.5.2
  # dart_pubspec_licenses: ^3.0.15
  # envied_generator: ^1.3.2
  # flutter_launcher_icons: ^0.14.4
  # flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # freezed: ^3.2.4
  # msix: ^3.16.13

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
  # fonts: Roboto (or JetBrains Mono)
  # --- REMOVE://BEGIN-OF-FONT-AREA ---
  # - assets/fonts/Noto_Sans/NotoSans-Bold.ttf
  # - assets/fonts/Noto_Sans/NotoSans-Regular.ttf
  # - assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.ttf
  # - assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.ttf
  # - assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.ttf
  # - assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.ttf
  # - assets/fonts/Noto_Sans_SC/NotoSansSC-Bold.ttf
  # - assets/fonts/Noto_Sans_SC/NotoSansSC-Regular.ttf
  # - assets/fonts/Noto_Sans_TC/NotoSansTC-Bold.ttf
  # - assets/fonts/Noto_Sans_TC/NotoSansTC-Regular.ttf
  # - assets/fonts/Noto_Sans_Thai/NotoSansThai-Bold.ttf
  # - assets/fonts/Noto_Sans_Thai/NotoSansThai-Regular.ttf
  # - assets/fonts/Noto_Sans_Thai_Looped/NotoSansThaiLooped-Bold.ttf
  # - assets/fonts/Noto_Sans_Thai_Looped/NotoSansThaiLooped-Regular.ttf
  # - assets/fonts/Noto_Sans_Hebrew/NotoSansHebrew-Bold.ttf
  # - assets/fonts/Noto_Sans_Hebrew/NotoSansHebrew-Regular.ttf
  # - assets/fonts/Noto_Kufi_Arabic/NotoKufiArabic-Bold.ttf
  # - assets/fonts/Noto_Kufi_Arabic/NotoKufiArabic-Regular.ttf
  # - assets/fonts/Noto_Sans_Arabic/NotoSansArabic-Bold.ttf
  # - assets/fonts/Noto_Sans_Arabic/NotoSansArabic-Regular.ttf
  # - assets/fonts/Noto_Sans_Devanagari/NotoSansDevanagari-Bold.ttf
  # - assets/fonts/Noto_Sans_Devanagari/NotoSansDevanagari-Regular.ttf
  # - assets/fonts/Noto_Sans_Bengali/NotoSansBengali-Bold.ttf
  # - assets/fonts/Noto_Sans_Bengali/NotoSansBengali-Regular.ttf
  # - assets/licenses/Noto_Sans/OFL.txt
  # - assets/licenses/Noto_Sans_KR/OFL.txt
  # - assets/licenses/Noto_Sans_JP/OFL.txt
  # - assets/licenses/Noto_Sans_SC/OFL.txt
  # - assets/licenses/Noto_Sans_TC/OFL.txt
  # - assets/licenses/Noto_Sans_Thai/OFL.txt
  # - assets/licenses/Noto_Sans_Thai_Looped/OFL.txt
  # - assets/licenses/Noto_Sans_Hebrew/OFL.txt
  # - assets/licenses/Noto_Kufi_Arabic/OFL.txt
  # - assets/licenses/Noto_Sans_Arabic/OFL.txt
  # - assets/licenses/Noto_Sans_Devanagari/OFL.txt
  # - assets/licenses/Noto_Sans_Bengali/OFL.txt
  # --- REMOVE://END-OF-FONT-AREA ---
  # - 'assets/images/splash-screen/splash.png'
  # - 'assets/images/app-icons/windows.png'
  # - 'assets/images/app-icons/windows_256.png'

flutter_launcher_icons:
  android: true
  min_sdk_android: 24
  image_path_android: 'assets/images/app-icons/android.png'
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: 'resources/images/app-icons/android.png'

  ios: true
  image_path_ios: 'assets/images/app-icons/ios.png'
  remove_alpha_ios: true
  background_color_ios: #000000

  web:
    generate: true
    # generated: false
    image_path: 'assets/images/app-icons/macos.png'

  windows:
    generate: true
    image_path: 'assets/images/app-icons/windows.png'
    icon_size: 48

  macos:
    generate: true
    image_path: 'assets/images/app-icons/macos.png'

  linux:
    generate: true
    image_path: 'assets/images/app-icons/linux.png'

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash-screen/splash.png

  android_12:
    image: 'assets/images/splash-screen/android12splash.png'
    color: "#000000"
    icon_background_color: "#000000"
  fullscreen: true

msix_config:
  display_name: Keyscope
  publisher_display_name: Infradise Inc.
  identity_name: com.infradise.keyscope
  msix_version: 1.0.0.2420
  publisher: 'CN=Infradise Inc., O=Infradise Inc., C=KR' # CN=4xxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
  logo_path: resources/images/app-icons/windows_msix.png # 400x400
  languages: "en, ko, ja, zh-CN, zh-TW, in, vi, th" # en-us, ko-kr
  architectures: "x64, arm64"
  store: true
  # sign_msix: true
  # install_certificate: false
  # certificate_path: ''
  # certificate_password: ''
  output_name: keyscope
  capabilities: internetClient

  # toast_activator:
  #   clsid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  #   arguments: "msix-args"
  #   display_name: "Keyscope Local Notifications"
